### ISSUE TITLE
Azure Resource Graph queries in the runbook disregard hybrid compute details

### ISSUE THREAD

**Issue by rvdhooff** [helderpinto/AzureUpdateManagerTools#1]
The Azure Resource Graph queries filter specifically on type == 'microsoft.compute/virtualmachines/patchinstallationresults', however as a result you disregard all results coming from for example the type microsoft.hybridcompute/machines/patchinstallationresults. 

You could change it the query to use : 

```kql
patchinstallationresources
| where type == 'microsoft.compute/virtualmachines/patchinstallationresults' or type == 'microsoft.hybridcompute/machines/patchinstallationresults'
```

However this might bring in problems in the future if additional types are added. You are maybe better of with this: 

```kql
patchinstallationresources
| where type endswith '/patchinstallationresults'
```

**Comment by Wiszanyel** [comment]
Thank you for the feedback @rvdhooff! checking now.

**Comment by Wiszanyel** [comment]
Fixed using @rvdhooff recommendation.
