### ISSUE TITLE
nextstagepropertiesjson is not working as expected

### ISSUE THREAD

**Issue by spotakash** [helderpinto/AzureUpdateManagerTools#2]
I followed all instructions and have prerequisites. But, it did not work with following exception. 
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/7689697/46d6e910-d659-450d-8a11-86687df1577e)

It seems like there is dependency of Az.ResourceGraph for 5.1 while module in automation account is only available for 7.2

If I tried to import 5.1, it throwa dependencies error of Az.Accounts should be > 2.9.1 
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/7689697/7446d40e-194e-4149-b816-a1fec9e151f4)
while it is only available for 2.8.0 
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/7689697/d8ecc6b7-c531-48c9-90f0-6d38ba070da6)

**Comment by Wiszanyel** [comment]
Hi @spotakash, import first the module Az.Accounts, after that import the module Az.ResourceGraph. Both with Runtime version 5.1:
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/74936319/be240290-7e1e-4e45-84a6-b42197eb4c99)

Let me know the results.

**Comment by spotakash** [comment]
@Wiszanyel I allowed me to import module with 5.1 following sequence suggested by you. But configuration still fails (with new error) You cannot call a method on a null-valued expression. (You cannot call a method on a null-valued expression.)

My nextstagepropertiesjson is as follows.
```
[

    {
        "stageName": "ubuntu22-preprod",
        "offsetDays": 2,
        "scope": [
            "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],
        "filter": {
            "resourceTypes": [
                "microsoft.compute/virtualmachines",
                "microsoft.hybridcompute/machines"
            ],
            "resourceGroups": [
            ],
            "tagSettings": {
                "tags": {
                    "aum-stage": [
                        "preprod"
                    ],
                    "os-name": [
                        "ubuntu22"
                    ]
                },
                "filterOperator": "All"
            },
            "locations": [],
            "osTypes": [
                "Linux"
            ]
        }
    },
    {
        "stageName": "ubuntu22-prod",
        "offsetDays": 4,
        "scope": [
            "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],
        "filter": {
            "resourceTypes": [
                "microsoft.compute/virtualmachines",
                "microsoft.hybridcompute/machines"
            ],
            "resourceGroups": [
            ],
            "tagSettings": {
                "tags": {
                    "aum-stage": [
                        "prod"
                    ],
                    "os-name": [
                        "ubuntu22"
                    ]
                },
                "filterOperator": "All"
            },
            "locations": [],
            "osTypes": [
                "Linux"
            ]
        }
    }
]

```

**Comment by helderpinto** [comment]
@spotakash , can you double check if the `MaintenanceConfigurationId` runbook parameter was set to a valid Resource ID of an **existing** Maintenance Configuration (the base one used for dev/test machines)? The resource ID must be in the following format: `/subscriptions/<subscription id>/resourcegroups/<resource group name>/providers/microsoft.maintenance/maintenanceconfigurations/<maintenance configuration name>`

**Comment by spotakash** [comment]
@helderpinto it is still throwing same error when schedule comes to trigger.
Interestingly, when I test this runbook in test mode, using same parameter it works fine. 
I sense, runbook is not able to pick up parameter correctly which were linked as part of schedule. Please note that I am not add ing "  " by myself but automatically getting added. Same json works fine when test runbook by same parameters
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/7689697/8d74eb08-25f5-44b1-8196-77eff00fcbd3)


Only this error is available 
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/7689697/ebd34bec-e6fc-4adb-ac1e-0c048b26eb57)

**Comment by helderpinto** [comment]
Thank you for reporting this, @spotakash. There were some recent ARG API changes in the query response payload which broke the script. There was also a problem with the script not dealing well with Maintenance Configuration IDs which were not lower-cased. The [most recent commit](https://github.com/helderpinto/AzureUpdateManagerTools/commit/66f9c43973b19b0af05bd408da25b4f0427170d1) of the [Create-StagedMaintenanceConfiguration.ps1](https://github.com/helderpinto/AzureUpdateManagerTools/blob/main/Create-StagedMaintenanceConfiguration.ps1) script fixed both issues. Can you please test it and report how it went?

**Comment by spotakash** [comment]
Thanks @helderpinto it moved but throw error as it detects existing maintenance configuration. It seems you may need to fix logic so that it updates existing pre-prod or prod (existing) maintenance configuration with new parameters. 
Dev- We trigger but PrePod/Prod will be updated based upon Dev. 

Error Message below

```
Failed
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 2:02:34 AM - Error: Code=InvalidResourceLocation; Message=The resource 'ubuntu22-preprod' already exists in location 'eastus' in resource group 'xxx'. A resource with the same name cannot be created in location 'eastus'. Please select a new resource name.
```

**Comment by helderpinto** [comment]
The logic is prepared to update existing maintenance configurations. It is based on an idempotent ARM template deployment. It seems the `ubuntu22-preprod` maintenance configuration is being updated with a `location` property that is different from the one it was created with. Can you please check the deployment details in the resource group where the base maintenance configuration is and validate whether the latest ARM deployment properties eventually conflicted?

![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/10661605/5e0fab31-d5b2-4a82-af83-51ba92d34329)

**Comment by spotakash** [comment]
No new deployment were being triggered 
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/7689697/484a5f91-5cec-4ee6-b7e8-8edccd6bda6a)

**Comment by spotakash** [comment]
@helderpinto I have resolved the issue by following a workaround. I deleted my previous maintenance configuration and ran the runbook again. It worked as expected and did not show any errors. I think the problem was caused by some intermittent caching issue that made my preprod and prod maintenance configuration appear in a different region than the base maintenance configuration. I verified that the runbook works fine with different parameters as well. You can close this issue now. 
Thank you for your guidance here and for fixing the script.
